# Pandas:-

## Series:- 1-D

In [1]:
import pandas as pd

In [2]:
a=(10,20,30)
b=pd.Series(a)
b

0    10
1    20
2    30
dtype: int64

In [3]:
a=(10,20,30)
index=("riya","riyu","sarva")
b=pd.Series(index,index=a)
b

10     riya
20     riyu
30    sarva
dtype: object

In [4]:
name=[100,200,300]
ans=pd.Series(name)
print(ans)

0    100
1    200
2    300
dtype: int64

In [5]:
data={"a":10,"b":20,"c":30}
answer=pd.Series(data)
answer

a    10
b    20
c    30
dtype: int64

In [7]:
data={"a":10,"b":20,"c":30}
answer=pd.Series(data,name="score")
answer

a    10
b    20
c    30
Name: score, dtype: int64

## DataFrame:-

In [9]:
data=[[1,2,3],[4,5,6],[7,8,9]]
df=pd.DataFrame(data)
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
data=[[1,2,3],[4,5,6],[7,8,9]]
df=pd.DataFrame(data)
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [13]:
data=[[1,2,3],[4,5,6],[7,8,9]]
df=pd.DataFrame(data,columns=["D1","D2","D3"])
df

   D1  D2  D3
0   1   2   3
1   4   5   6
2   7   8   9

In [14]:
data=[[1,2,3],[4,5,6],[7,8,9]]
df=pd.DataFrame(data,columns=["D1","D2","D3"],index=["r1","r2","r3"])
df

    D1  D2  D3
r1   1   2   3
r2   4   5   6
r3   7   8   9

In [16]:
india={"dhurav":[100,200,20],"dhoni":[200,190,340]}
c=pd.DataFrame(india)
c

   dhurav  dhoni
0     100    200
1     200    190
2      20    340

In [5]:
data1=pd.read_csv("auto-mpg.csv")
df=pd.DataFrame(data1)
df

NameError: name 'pd' is not defined

In [18]:
df.ndim

2

In [19]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [20]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [23]:
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl

In [21]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [24]:
df.tail(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
388,26.0,4,156.0,92,2585,14.5,82,1,chrysler lebaron medallion
389,22.0,6,232.0,112,2835,14.7,82,1,ford granada l
390,32.0,4,144.0,96,2665,13.9,82,3,toyota celica gt
391,36.0,4,135.0,84,2370,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90,2950,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [4]:
df.ndim()

NameError: name 'df' is not defined

In [26]:
df.set_index(df["mpg"])
df
#tempory change

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [27]:
p=df.set_index(df["mpg"])
p

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
mpg,,,,,,,,,
18.0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
15.0,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
18.0,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
16.0,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
17.0,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
27.0,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
44.0,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
32.0,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
28.0,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
31.0,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [28]:
df.set_index(df["mpg"],inplace=True)
df
#permanent change in csv file

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
mpg,,,,,,,,,
18.0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
15.0,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
18.0,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
16.0,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
17.0,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
27.0,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
44.0,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
32.0,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
28.0,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
31.0,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [1]:
df.size()

NameError: name 'df' is not defined

SyntaxError: invalid syntax (<ipython-input-7-a4e7ade3e419>, line 1)