In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

data=pd.read_csv("car data.csv")
df=pd.DataFrame(data)
df.loc[:,"Age_car"]=2023-df["Year"]
df

x=df[["Age_car","Kms_Driven","Fuel_Type","Seller_Type","Transmission"]]
y=df["Selling_Price"]
x=pd.get_dummies(x)
print(x)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
z=model.fit(x_train,y_train)
pre=model.predict(x_test)
acc=r2_score(y_test,pre)
print(acc)

     Age_car  Kms_Driven  Fuel_Type_CNG  ...  Seller_Type_Individual  Transmission_Automatic  Transmission_Manual
0          9       27000          False  ...                   False                   False                 True
1         10       43000          False  ...                   False                   False                 True
2          6        6900          False  ...                   False                   False                 True
3         12        5200          False  ...                   False                   False                 True
4          9       42450          False  ...                   False                   False                 True
..       ...         ...            ...  ...                     ...                     ...                  ...
296        7       33988          False  ...                   False                   False                 True
297        8       60000          False  ...                   False                   False                 True
298       14       87934          False  ...                   False                   False                 True
299        6        9000          False  ...                   False                   False                 True
300        7        5464          False  ...                   False                   False                 True

[301 rows x 9 columns]
0.591149566336626

In [20]:
df1=df.sample(n=1)
df1

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner  Age_car
229      i20  2012            3.1           6.79       52132    Diesel      Dealer       Manual      0       11

In [23]:
#x=df[["Age_car","Kms_Driven","Fuel_Type","Seller_Type","Transmission"]]
x_train
print(model.predict([[11,52132,0,0,1]],y))

TypeError: LinearModel.predict() takes 2 positional arguments but 3 were given

Write a program to create a Model using linear regression to predict the wine quality using the csv file provided named 
“winequality.csv”. Do the required process in the data before making a model. 
If you find any null value in “winequality.csv” then replace null value with mean value of respected columns.
Find co-efficient, intercept and mean squared error.
also Predict the quality of red wine for the following data:                       
fixed acidity: 8            
vola le acidity: 0.4       
citric acid: 0.40                
residual sugar: 15          
chlorides: 0.048                  
free sulfur dioxide: 40      
total sulfur dioxide: 150     
density: 0.99                  
pH: 3                      
sulphates: 0.45                
alcohol: 10.5

In [38]:
df = pd.read_csv('winequalityN.csv')


df.fillna(df.mean(numeric_only=True), inplace=True)


df = pd.get_dummies(df, columns=['type'], drop_first=True)

x = df.drop(columns=['quality'])
y = df['quality']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

print(f"Co-efficients: {model.coef_}")
print(f"Intercept: {model.intercept_}")

pre = model.predict(x_test)
print(f"Mean Squared Error: {mean_squared_error(y_test, pre)}")
print(f"R2 Score: {r2_score(y_test, pre) * 100:.2f}%")

new_data = pd.DataFrame({
    'fixed acidity': [8],
    'volatile acidity': [0.4],
    'citric acid': [0.40],
    'residual sugar': [15],
    'chlorides': [0.048],
    'free sulfur dioxide': [40],
    'total sulfur dioxide': [150],
    'density': [0.99],
    'pH': [3],
    'sulphates': [0.45],
    'alcohol': [10.5],
    'type_white': [0] 
})

prediction = model.predict(new_data)
print(f"\nPredicted Quality for provided Red Wine data: {prediction[0]:.2f}")

Co-efficients: [ 7.87101728e-02 -1.47184596e+00 -4.10628390e-02  6.07094439e-02
 -6.70234962e-01  5.27960941e-03 -1.64982333e-03 -9.56364968e+01
  4.40108968e-01  7.34056038e-01  2.27705826e-01 -3.41465792e-01]
Intercept: 96.68943584121232
Mean Squared Error: 0.47142125991978623
R2 Score: 34.05%

Predicted Quality for provided Red Wine data: 6.92

### KNN Model:-

In [39]:
import pandas as pd
data=pd.read_csv("Fish.csv")
df=pd.DataFrame(data)
df

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

x=df.drop("Species",axis=1)
y=df["Species"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
pre=model.predict(x_test)
acc=accuracy_score(y_test,pre)
acc

0.53125

In [44]:
print(model.predict([[242.0,23.2,25.4,30.0,11.5200,4.0200]]))

['Perch']

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [42]:
df

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [58]:
s={}
for i in range(1,21):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
    model=KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    pre=model.predict(x_test)
    acc=accuracy_score(y_test,pre)
    s[i]=acc
max(s.values())

0.6875